name: audio_mixer
description: Audio Mixer UI
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_xlider: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/



  #Fonts
  fonts:
    - family: LED
      fonts:
        - asset: fonts/digital-counter-7.regular.ttf